### ISSUE TITLE
Segmentation Violation when trying a new tracker digitizer (Probably due to LCIO<->EDM4Hep converter)

### ISSUE THREAD

**Issue by jessy-daniel** [key4hep/CLDConfig#64]
### Check duplicate issues.

- [x] Checked for duplicates

### Goal

Dear all,

I am trying to create a new detailed digitizer for tracking system. the new digitizer is fully key4hep and do not need MarlinWrapper anymore. However, I get a segmentation violation which is maybe linked to the EDM4Hep->LCIO converter. COuld you please have a look ?

## 1. Context  
The new digitizer is available on this branch: [VTXdigiDetailed](https://github.com/jessy-daniel/k4RecTracker/tree/New_Detailed_VTXdigitizer).  
The CLD configuration to use it is available here: [CLDConfig](https://github.com/jessy-daniel/CLDConfig/tree/detailled_digitizer).  

More specifically:  
- **TrackingDigi.py** has been modified to use *VTXdigiDetailed* instead of the Marlin processor.  
- An **EDM4hep2LCIO converter** has been added in *ConformalTracking.py* to convert the *TrackerHitPlaneCollection* back into a format readable by Marlin.  
- The new tracker requires segmentation, implemented in this *k4geo* branch: [Add_pixels_tracker](https://github.com/jessy-daniel/k4geo/tree/Add_pixels_tracker).  

## 2. Initial issue (resolved but potentially related)  
With this CLDConfig commit: [00849792dec2170710bd14b079ee3f6976cfba6a](https://github.com/key4hep/CLDConfig/commit/00849792dec2170710bd14b079ee3f6976cfba6a), the only difference from the current version is that during the format conversion of *TrackerHitPlaneCollections*, I kept the same collection name for both the LCIO and EDM4HEP versions.  

When I ran the reconstruction (commenting out the line related to **Refit** at line 131 in *CLDReconstruction.py* to avoid a segmentation violation, see next point), I got numerous warnings in the log:  

`Couldn't find an EDM4hep TrackerHit for an LCIO TrackerHit when resolving relations for a Track`

These warnings disappear if I don’t define the **Du** and **Dv** variables in *TrackerHitPlane* (lines 554-555 of *VTXdigitizerDetailed.cc*) and reappear if I uncomment these lines. I suspect an issue with the EDM4HEP → LCIO conversion.  

The issue was resolved by enforcing different names for the LCIO and EDM4HEP collections during conversion ([commit](https://github.com/key4hep/CLDConfig/commit/027418f51c560e89daa7cdfe74936e4eea87ab05)), but I don’t understand why this works. Moreover, it seems suboptimal to unnecessarily double the number of collections.  

## 3. Current issue (segmentation violation with Refit)  
When I run the full reconstruction (**including Refit**) with the new digitizer, I get a **segmentation violation** that is quite hard to understand (see log file attached).

Once again, **this segmentation violation disappears if I comment out the lines defining the Du and Dv variables** in *TrackerHitPlane* (lines 554-555 of *VTXdigitizerDetailed.cc*). Obviously, i need to set those variables for the reconstruction step.

I don’t see how these variables could affect **Refit**, which only takes as input the output from *ConformalTracking*. Especially since this output seems, at first glance, to be roughly the same as the default output obtained with the Marlin digitizer…  By looking at the log, it seems that there are issues with PandoraPFA such that I think about a conversion EDM4HEP → LCIO issue

Note : There are some additional errors in the log such that : 
`Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for /tmp/root/spack-stage/spack-stage-physsim-5f2c34dd5a6b60fc423bbe5a91099e9b10ea1027_develop-xhjoh4vnfkvufiaz6gzrzkvr7nqsc2h7/spack-src/include/physsim/ANL4DVector.h
   requested to autoload type ANL4DVector`
those errors are irrelevant as also present in the nominal case with nominal digitizer.

I hope this description is clear enough, even though I have tested several things.  
Thanks in advance for your help!  

The log:
[Log_reconstruction.log](https://github.com/user-attachments/files/18782653/Log_reconstruction.log)

### Operating System and Version

Linux 9.5 (default lxplus)

### compiler

GCC 14.2

### The version of the key4hep stack

Nightlies in /cvmfs/sw-nightlies.hsf.org/key4hep

### Package Version

https://github.com/jessy-daniel/CLDConfig/tree/detailled_digitizer

## 4. Reproducer

In lxplus: 

```
cd in a new directory
#Setup the nightlies
source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
git clone git@github.com:jessy-daniel/k4geo.git

#Install k4geo branch and setup it
cd k4geo
git checkout Add_pixels_tracker
mkdir build install
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=../install
make install -j 8
cd ../..
source k4geo/install/bin/thisk4geo.sh
export DD4HEP_LIBRARY_PATH=$PWD/k4geo/install/lib/:$DD4HEP_LIBRARY_PATH
export CMAKE_PREFIX_PATH=$PWD/k4geo/install/:$CMAKE_PREFIX_PATH
export LCGEO=$PWD/k4geo
export lcgeo_DIR=$PWD/k4geo
export K4GEO=$PWD/k4geo
export k4geo_DIR=$PWD/k4geo

#Install k4RecTracker branch and setup it
git clone git@github.com:jessy-daniel/k4RecTracker.git
cd k4RecTracker
git checkout New_Detailed_VTXdigitizer
mkdir build install
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=../install
make install -j 8
cd ../..
export K4RECTRACKER=$PWD/k4RecTracker/install/share/k4RecTracker; PATH=$PWD/k4RecTracker/install/bin/:$PATH; CMAKE_PREFIX_PATH=$PWD/k4RecTracker/install/:$CMAKE_PREFIX_PATH; LD_LIBRARY_PATH=$PWD/k4RecTracker/install/lib:$PWD/k4RecTracker/install/lib64:$LD_LIBRARY_PATH; export PYTHONPATH=$PWD/k4RecTracker/install/python:$PYTHONPATH

#Install the CLDConfig branch
git clone git@github.com:jessy-daniel/CLDConfig.git
cd CLDConfig
git checkout detailled_digitizer
cd ..

#Generate events
ddsim --steeringFile $CLDCONFIG/share/CLDConfig/cld_steer.py \
      --compactFile $K4GEO/FCCee/CLD/compact/CLD_o2_v07/CLD_o2_v07.xml \
      --enableGun \
      --gun.distribution uniform \
      --gun.energy "10*GeV" \
      --gun.particle mu- \
      --numberOfEvents 100 \
      --outputFile Step1_edm4hep.root

#Run the digitisation and reconstruction
cd CLDConfig/CLDConfig
k4run CLDReconstruction.py --inputFiles ../../Step1_edm4hep.root --outputBasename Step2 -n 100
#There is a segmentation violation at this step
```

It runs when commenting lines 554-555 of *VTXdigitizerDetailed.cc* (but the reconstruction then does not know the uncertainty on position) or by commenting line 131 in *CLDReconstruction.py* (Not runing **Refit**)

**Comment by Zehvogel** [comment]
Segfault comes from this line as far as I can tell:
https://github.com/iLCSoft/MarlinReco/blob/dcaff65b1487c5ecfa8691eb57f3575f5902a636/Analysis/RecoMCTruthLink/src/RecoMCTruthLinker.cc#L2101

**Comment by jessy-daniel** [comment]
Hi Leonhard, 
Indeed, I can try to convert the relations. Also it makes me realize that the name of the relations for recoMCTruthLinker is different than the names I put in https://github.com/jessy-daniel/CLDConfig/blob/detailled_digitizer/CLDConfig/Tracking/TrackingDigi.py. I
 will readapt the names and see if it works, in addition to adding the relation conversion. 

Do you have ideas about the first error I had (point 2.) as it is a unefficient to double the number of collections as I need to rename the collection when processing the conversion ?

**Comment by jessy-daniel** [comment]
Ok, thank you very much !

**Comment by jessy-daniel** [comment]
So, here is the new version of CLDConfig : https://github.com/jessy-daniel/CLDConfig/tree/detailled_digitizer
I names de collections for EDM4Hep as <name>EDM4HEP so that the name for LCIO version is correct with the next steps (RecoMCTruthLinker, etc. 
using this CLDConfig i do not have segmentation fault but I have the following error : 

[log_ConvertRelations.txt](https://github.com/user-attachments/files/18785786/log_ConvertRelations.txt)

This is certainly because this time it doesn't even find a relation has the converter seems not to convert the relation...

**Comment by jessy-daniel** [comment]
Thanks ! I am not sure where you want me to convert the SimTrackerHit. in the converter attached to ConformalTracking ? or should I attach a converter to VTXdigiDetailed to convert before the SimTrackerHit before the digitizer ?

For your second solution, that means we do not run the Overlay, i do not know what it does ?

**Comment by tmadlener** [comment]
> I think we need to convert the `SimTrackerHits` from lcio to edm4hep in the same conversion step as the relation/link between `TrackerHits` and `SimTrackerHits` as otherwise the objects will not be there at that step (right @tmadlener?)

So at least in principle the conversion of the relation / link doesn't have to happen in the same conversion step. We keep track of all the things that are converted in either direction so we should be able to link things in different conversion steps. Obviously if you need the links / LCRelations in the wrapped Marlin processor you need to convert them before that is run. In this case it should probably be done on the output of the digitizer (assuming that that actually creates a link between the `SimTrackerHit`s and the output `TrackerHit`s).

What I am not entirely sure of is how having different names of collections might affect our strategy of keeping track of converted objects.

**Comment by jessy-daniel** [comment]
Dear @tmadlener,

So you would suggest that I attach a converter EDM4Hep->LCIO to the digitizer ? How do I know that the converter will be run in the output and not input ?

**Comment by Zehvogel** [comment]
It is only possible to attach converters to MarlinWrapper algorithms so you cannot attach it to your new gaudi-native digitizer.

Please try it with the same setup as before with the converter attached to conformal tracking, make all the names the same without any EDM4HEP/LCIO endings and report back what happens.

**Comment by jessy-daniel** [comment]
Thank you again for your help and sorry if I do not always understand the solution.
When making all the names the same and keeping the converter attached to Conformaltracking, here is what I get : 

[log_ConvertRelations_SameNames.txt](https://github.com/user-attachments/files/18787383/log_ConvertRelations_SameNames.txt)

**Comment by jessy-daniel** [comment]
> Can you try to increase the `OutputLevel` of the EDM4hep to LCIO converter that should convert the outputs to `DEBUG`? It should then have a bit more output and also tell us which collections it is actually converting.

For sure, here is the output with debug level : 

[log_DEBUG_ConvertRelations_SameNames.txt](https://github.com/user-attachments/files/18787560/log_DEBUG_ConvertRelations_SameNames.txt)

**Comment by Zehvogel** [comment]
Looks like it fails to match the edm4hep `TrackerHit` from the link to a converted lcio one.

Do the digitized tracker hits appear in the edm4hep output file?

**Comment by jessy-daniel** [comment]
> Looks like it fails to match the edm4hep `TrackerHit` from the link to a converted lcio one.
> 
> Do the digitized tracker hits appear in the edm4hep output file?

yes it does appear

**Comment by Zehvogel** [comment]
> I don't know, but can we replace these parts (and their equivalent in the other direction) by using `TrackerHit3D`?

Now also I got confused :D I meant we should use `TrackerHit` (the interface) for everything. The naming in the converter is still a bit mixed, a `TrackerHit3D` is in `objectMappings.trackerHits` and a `TrackerHitPlane` in `objectMappings.trackerHitPlanes` 🥴

**Comment by Zehvogel** [comment]
So in conclusion I think the line where it goes wrong in the conversion is this one:
```c++
    } else if (const auto trackerHitSimTrackerHitLink =
                   dynamic_cast<const edm4hep::TrackerHitSimTrackerHitLinkCollection*>(coll)) {
      relationColls.emplace_back(name, createLCRelationCollection(*trackerHitSimTrackerHitLink, objectMaps.trackerHits,
                                                                  objectMaps.simTrackerHits));
```
where we use the `objectMaps.trackerHits` which is in reality a map of `TrackerHit3D`

https://github.com/key4hep/k4EDM4hep2LcioConv/blob/a4f30647206014db73d446f9613f7c2e59e5698e/k4EDM4hep2LcioConv/include/k4EDM4hep2LcioConv/k4EDM4hep2LcioConv.ipp#L773-L776

**Comment by jessy-daniel** [comment]
> [@jessy-daniel](https://github.com/jessy-daniel) You might get further if you try to use an `edm4hep::TrackerHitPlaneSimTrackerHitLinkCollection` as the output of your digitizer, but don't be surprised if something else breaks down the line... you are stepping on untested territory :)

Hi @Zehvogel , thank you for this clear explanation that can indeed explain the issue. 
It seems that edm4hep::TrackerHitPlaneSimTrackerHitLinkCollection does not exists, I do not find it nowhere and I have compilation errors saying it does not exist when trying to change the output format of this link collectiion

**Comment by tmadlener** [comment]
For the MC - reco link it shouldn't matter whether it's a `TrackerHit3D` or a `TrackerHitPlane`. The part that is missing, is in the converter to also consider the `TrackerHitPlane`s for these links. I am currently working on a fix for that.

**Comment by tmadlener** [comment]
https://github.com/key4hep/k4EDM4hep2LcioConv/pull/112 should fix this, but I haven't tested it yet on your specific example.

**Comment by tmadlener** [comment]
It's a bit more involved in this case: You have to build and install the k4EDM4hep2LcioConv library (as you already did), but you than also have to build your own version of the k4MarlinWrapper library / Gaudi algorithms. If you do this you have to make sure that you put the installed library directory onto `LD_LIBRARY_PATH` and the installed python directory onto the `PYTHONPATH`. **The easiest way to achieve this is the use of [`k4_lcoal_repo`](https://key4hep.github.io/key4hep-doc/developing-key4hep-software/SinglePackage.html#adapt-the-environment-with-k4-local-repo)** (this effectively does what you are currently doing manually).

So effectively something like
```bash
git clone https://github.com/key4hep/k4MarlinWrapper
cd k4MarlinWrapper
cmake -B build -S . -DCMAKE_INSTALL_PREFIX=$(pwd)/install -GNinja
cmake --build build --target install
k4_local_repo
```

With this (and all your evnironment modifications) you should be able to get to a fixed version of the conversion inside the Marlin wrapper.

**Comment by jessy-daniel** [comment]
Hi @tmadlener,

Thank you for this help. i did not know about the k4_local_repo command. it will change my life instead of changing manually the environment variables. 
I tried the reconstruction with this fixed converter but I still get the same errors where it couldn't find the proper object for conversion : 

[Log_reconstruction_fixed_converter.log](https://github.com/user-attachments/files/18823374/Log_reconstruction_fixed_converter.log)

**Comment by tmadlener** [comment]
Turns out there is another bug in k4MarlinWrapper which is fixed by https://github.com/key4hep/k4MarlinWrapper/pull/221

With both these PRs in place, I can run over all events in your example (without having checked the output).

**Comment by tmadlener** [comment]
Both PRs are merged and should be picked up by the nightlies tomorrow. Letting @jessy-daniel close this once it is confirmed things also work on their end.

**Comment by jessy-daniel** [comment]
Dear @tmadlener , Things work great now. Thank you very much. I close the issue
